### ISSUE TITLE
extraData

### ISSUE THREAD

**Issue by kamilpogo** [matthewturner/Eventually#16]
extraData was removed from EvtListener (probably to save some memory). However it is very useful to have the option to assign extraData to a listener (e.g. an object uses a listener and in the callback the object has to be assigned. extraData can be used to store a pointer to the object that owns the listener)

I would propose to reintroduce extraData to EvtListener that was removed here: https://github.com/matthewturner/Eventually/commit/0a3f2e4e6d2bd3841933bf05833182004d1b4a03#diff-2f154c55f0e4e9f7f0ecadefc29fde25da27e0fe45a7661e8c40c0caff81cbca

**Comment by kamilpogo** [comment]
PR: https://github.com/matthewturner/Eventually/pull/17/files

**Comment by matthewturner** [comment]
Thanks for the suggestion. I removed it because it was outputting compiler warnings in PlatformIO and I didn't know what to do with them. It doesn't seem to do that anymore. I always meant to add this capability back in so it's good to hear someone would find it valuable.

I've put a small question on your PR. Thanks for the contribution!

**Comment by hmueller01** [comment]
new approach with #25 ...

**Comment by matthewturner** [comment]
Fixed by #25
